author_id = "olle"
app_id = "lampy"
author_name = "Olle & Catboots"
app_name = "Lampy"

[files]
spritesheet = { path = "assets/spritesheet.png", palette="steam-lords" }
font = { path = "assets/kenney_16x16.fff" }
font_points = { path = "assets/pico8_4x6.fff" }
music_loop = { path = "assets/loop.wav" }
pling = { path = "assets/score.wav" }

[badges]
1 = { name = "wins", steps = 10, descr = "Win 10 times" }
2 = { name = "deaths", steps = 10, descr = "Die 10 times" }

[cheats]
restart = 1
debug = 2
add-points = 3

# https://lospec.com/palette-list/steam-lords
[palettes.steam-lords]
1 = 0x213b25
2 = 0x3a604a
3 = 0x4f7754
4 = 0xa19f7c
5 = 0x77744f
6 = 0x775c4f
7 = 0x603b3a
8 = 0x3b2137
9 = 0x170e19
10 = 0x2f213b
11 = 0x433a60
12 = 0x4f5277
13 = 0xde5d49
14 = 0xe533e8
15 = 0x70eb44
16 = 0x43b1e8
